
import { Country, Consultancy } from './types';

export const COUNTRIES: Country[] = [
  {
    id: 'ca',
    name: 'Canada',
    flag: '🇨🇦',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=2000&auto=format&fit=crop',
    description: 'The world leader in welcoming skilled immigrants through transparent point-based systems.',
    economy: 'Stable G7 economy with strong focus on natural resources, tech, and healthcare. Known for its resilience and high GDP per capita.',
    jobMarket: 'Critical demand in tech (Toronto/Vancouver), healthcare, and engineering sectors. Huge shortage in trades and social services.',
    education: 'Home to world-class research institutions like University of Toronto and UBC. Offers the generous Post-Graduation Work Permit (PGWP).',
    prBenefits: 'Universal healthcare, high standard of living, and a rapid 3-year path to citizenship for permanent residents.',
    history: 'A nation built on immigration, Canada transitioned from a British colony to a sovereign multicultural democracy with a rich indigenous heritage.',
    geography: 'The second-largest country in the world, spanning six time zones with diverse climates from temperate rain forests to arctic tundras.',
    politics: 'A constitutional monarchy and federal parliamentary democracy known for social liberal policies and human rights advocacy.',
    studentInfo: 'Canada is the top choice for international students due to its welcoming culture, work-while-you-study permits, and clear paths to permanent residency after graduation.',
    jobInfo: 'The Canadian job market is currently experiencing high vacancy rates. Skilled workers can benefit from high salaries and excellent work-life balance across all major provinces.',
    cities: [
      'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'Calgary', 'Edmonton', 
      'Winnipeg', 'Quebec City', 'Hamilton', 'London (ON)', 'Victoria', 
      'Halifax', 'Saskatoon', 'Regina', 'St. John\'s', 'Fredericton', 
      'Kingston', 'Waterloo', 'Guelph', 'Sherbrooke', 'Windsor', 'Kelowna'
    ],
    visas: [
      {
        id: 'ca-ee',
        name: 'Express Entry (FSWP)',
        purpose: 'Direct Permanent Residency for skilled professionals.',
        eligibility: ['Age under 45', '1 year continuous work', 'CLB 7 language skills'],
        qualifications: 'Post-secondary degree (ECA required).',
        experience: 'Minimum 1 year in NOC TEER 0, 1, 2, or 3.',
        language: 'IELTS 6.0+ in all modules or CELPIP 7+.',
        finance: '$13,757 CAD for single applicant.',
        processingTime: '6 months',
        settlementPotential: true
      },
      {
        id: 'ca-sp',
        name: 'Study Permit',
        purpose: 'Entry for students at Designated Learning Institutions.',
        eligibility: ['LOA from DLI', 'Proof of funds', 'Police clearance'],
        qualifications: 'Varies by program (Diploma/Degree).',
        experience: 'N/A',
        language: 'IELTS 6.0-6.5 typically.',
        finance: 'Tuition + $20,635 CAD living costs.',
        processingTime: '4-12 weeks',
        settlementPotential: true
      },
      {
        id: 'ca-suv',
        name: 'Start-up Visa Program',
        purpose: 'For entrepreneurs with a business idea supported by a designated organization.',
        eligibility: ['Letter of support from designated org', 'Language skills CLB 5', 'Settlement funds'],
        qualifications: 'N/A',
        experience: 'Entrepreneurial experience.',
        language: 'CLB 5 in all modules.',
        finance: '$13,757 CAD+.',
        processingTime: '12-16 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=2000&auto=format&fit=crop',
    description: 'A global cultural and financial powerhouse offering prestigious career opportunities.',
    economy: 'The world\'s sixth-largest economy, dominated by the services sector, particularly banking, insurance, and business services.',
    jobMarket: 'Chronic shortages in the NHS, technology sectors, secondary education, and various skilled trades following Brexit.',
    education: 'Global gold standard for higher education with institutions like Oxford, Cambridge, and Imperial College London leading world rankings.',
    prBenefits: 'Path to Indefinite Leave to Remain (ILR) after 5 years of residency, providing full access to the UK social system and healthcare.',
    history: 'From the Roman era through the Industrial Revolution to its modern status as a global influencer, the UK has shaped much of modern law and technology.',
    geography: 'An island nation comprising England, Scotland, Wales, and Northern Ireland, featuring diverse landscapes from the Scottish Highlands to the rolling hills of Kent.',
    politics: 'A parliamentary democracy with a constitutional monarch, the UK is a central player in the G7, NATO, and the Commonwealth.',
    studentInfo: 'With the Graduate Route visa, students can now stay and work in the UK for 2 years (3 years for PhDs) after completing their studies at recognized universities.',
    jobInfo: 'The UK Skilled Worker visa route is highly accessible for those with job offers. Tech hubs in London, Manchester, and Edinburgh offer high earning potential.',
    cities: [
      'London', 'Oxford', 'Cambridge', 'Manchester', 'Birmingham', 'Edinburgh', 
      'Glasgow', 'Bristol', 'Sheffield', 'Leeds', 'Liverpool', 'Nottingham', 
      'Southampton', 'Newcastle upon Tyne', 'Cardiff', 'Belfast', 'Coventry', 
      'Leicester', 'Brighton', 'Exeter', 'York', 'Bath', 'Durham', 'Reading', 
      'Portsmouth', 'Aberdeen', 'Dundee', 'Swansea', 'Plymouth', 'Hull'
    ],
    visas: [
      {
        id: 'uk-sw',
        name: 'Skilled Worker Visa',
        purpose: 'Long-term work for approved UK sponsors.',
        eligibility: ['Certificate of Sponsorship', 'Minimum salary threshold (£38,700)', 'English B1'],
        qualifications: 'Job must be at RQF level 3 or above.',
        experience: 'Relevant to the job offer.',
        language: 'B1 level (IELTS 4.0+).',
        finance: '£1,270 in personal savings.',
        processingTime: '3-8 weeks',
        settlementPotential: true
      },
      {
        id: 'uk-gt',
        name: 'Global Talent Visa',
        purpose: 'For leaders in academia, tech, and arts.',
        eligibility: ['Endorsement by designated body', 'Exceptional promise/talent'],
        qualifications: 'Doctorate or equivalent international standing.',
        experience: 'Proven track record in field.',
        language: 'N/A',
        finance: 'N/A',
        processingTime: '4-8 weeks',
        settlementPotential: true
      },
      {
        id: 'uk-if',
        name: 'Innovator Founder Visa',
        purpose: 'For entrepreneurs starting an innovative business.',
        eligibility: ['Endorsement by approved body', 'Innovative, viable, scalable business plan', 'English B2'],
        qualifications: 'N/A',
        experience: 'Relevant business experience.',
        language: 'B2 level (IELTS 5.5+).',
        finance: 'Sufficient funds to support self.',
        processingTime: '3 weeks',
        settlementPotential: true
      },
      {
        id: 'uk-sv',
        name: 'Student Visa',
        purpose: 'For students accepted at UK educational institutions.',
        eligibility: ['CAS from licensed sponsor', 'Proof of funds', 'English B2'],
        qualifications: 'Varies by course.',
        experience: 'N/A',
        language: 'B2 level.',
        finance: 'Course fees + living costs (£1,334/mo in London).',
        processingTime: '3 weeks',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'de',
    name: 'Germany',
    flag: '🇩🇪',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=2000&auto=format&fit=crop',
    description: 'Europe\'s industrial engine with a massive demand for international talent.',
    economy: 'Largest economy in Europe and fourth-largest globally, famous for precision engineering, automotive, and chemical industries.',
    jobMarket: 'Extreme demand for software developers, engineers, healthcare workers, and specialized technicians across the country.',
    education: 'Known for tuition-free public universities and a dual vocational training system that is copied worldwide.',
    prBenefits: 'Permanent residency available after 3-5 years. Excellent social safety net, pension system, and central European travel access.',
    history: 'A nation that reinvented itself post-WWII into a peaceful industrial giant and the leading force of European integration.',
    geography: 'Located in the heart of Europe, Germany features varied landscapes from the North Sea coast to the Bavarian Alps in the south.',
    politics: 'A federal parliamentary republic with a high emphasis on social market economy and consensus-based governance.',
    studentInfo: 'International students in Germany enjoy low costs and high standards. Most public universities charge zero tuition fees, even for non-EU students.',
    jobInfo: 'The new Opportunity Card (Chancenkarte) allows points-based entry for job seekers. Skilled professionals can also apply for the EU Blue Card.',
    cities: [
      'Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 
      'Cologne', 'Leipzig', 'Heidelberg', 'Aachen', 'Bonn', 'Dresden'
    ],
    visas: [
      {
        id: 'de-ebc',
        name: 'EU Blue Card',
        purpose: 'Highly qualified work residency.',
        eligibility: ['German university degree', 'Annual salary €45k+', 'Job match'],
        qualifications: 'University degree (Anabin recognized).',
        experience: 'Professional match to role.',
        language: 'German not strictly required (B1 for fast PR).',
        finance: 'Employment contract salary.',
        processingTime: '2-3 months',
        settlementPotential: true
      },
      {
        id: 'de-jsv',
        name: 'Opportunity Card (Chancenkarte)',
        purpose: 'Points-based job search entry.',
        eligibility: ['6 points in scoring system', 'Base A1 German', 'Proof of funds'],
        qualifications: 'Vocationally or academically trained.',
        experience: '2 years professional experience.',
        language: 'A1 German or B2 English.',
        finance: '€1,027 per month (blocked account).',
        processingTime: '2 months',
        settlementPotential: true
      },
      {
        id: 'de-sev',
        name: 'Self-Employment Visa',
        purpose: 'For entrepreneurs and freelancers.',
        eligibility: ['Economic interest', 'Financing secured', 'Positive impact on economy'],
        qualifications: 'Relevant to business.',
        experience: 'Business plan required.',
        language: 'German B1 recommended.',
        finance: 'Proof of self-sufficiency.',
        processingTime: '3-6 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'us',
    name: 'United States',
    flag: '🇺🇸',
    image: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?q=80&w=2000&auto=format&fit=crop',
    description: 'The ultimate destination for innovation, entrepreneurship, and high-tech careers.',
    economy: 'The world\'s largest economy by nominal GDP, characterized by high productivity and technological innovation.',
    jobMarket: 'Highly competitive and lucrative. Strong demand for AI specialists, data scientists, healthcare practitioners, and entrepreneurs.',
    education: 'Home to the Ivy League and world-leading research universities that attract the brightest minds from across the globe.',
    prBenefits: 'The "Green Card" offers permanent residency, high earning potential, and the eventual path to US citizenship.',
    history: 'A nation founded on the principles of liberty, the US has grown from 13 colonies to a global superpower and cultural trendsetter.',
    geography: 'Vast and diverse, from the arid deserts of the Southwest to the lush forests of the Northwest and the bustling East Coast megalopolis.',
    politics: 'A federal constitutional republic with a three-branch system of government, emphasizing individual rights and state sovereignty.',
    studentInfo: 'The Optional Practical Training (OPT) program allows F-1 students to work in the US for up to 3 years (for STEM fields) after graduation.',
    jobInfo: 'While visa processes like the H-1B are competitive, the US remains the highest-paying market in the world for skilled technical and medical roles.',
    cities: [
      'New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'Boston', 
      'Seattle', 'Washington D.C.', 'Austin', 'Atlanta', 'Philadelphia', 'Miami'
    ],
    visas: [
      {
        id: 'us-h1b',
        name: 'H-1B Specialty Occupation',
        purpose: 'Specialized employment in high-tech fields.',
        eligibility: ['Bachelors degree', 'Employer sponsorship', 'Lottery selection'],
        qualifications: 'Specific degree for specialized role.',
        experience: 'N/A (Entry level allowed).',
        language: 'Fluent English.',
        finance: 'Employer paid prevailing wage.',
        processingTime: '3-6 months (Lottery dependent)',
        settlementPotential: true
      },
      {
        id: 'us-l1',
        name: 'L-1 Intracompany Transfer',
        purpose: 'Managerial/Executive transfer.',
        eligibility: ['Worked for overseas parent 1/3 years', 'Executive/Managerial role'],
        qualifications: 'Specialized knowledge or executive role.',
        experience: '1 year with current company.',
        language: 'Fluent English.',
        finance: 'N/A',
        processingTime: '2-4 months',
        settlementPotential: true
      },
      {
        id: 'us-o1',
        name: 'O-1 Extraordinary Ability',
        purpose: 'For individuals with extraordinary ability in sciences, arts, education, business, or athletics.',
        eligibility: ['National/International acclaim', 'Extraordinary ability in field', 'Job offer/Sponsorship'],
        qualifications: 'Awards, publications, high salary, or other evidence of acclaim.',
        experience: 'Proven track record of excellence.',
        language: 'N/A',
        finance: 'N/A',
        processingTime: '2-4 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'au',
    name: 'Australia',
    flag: '🇦🇺',
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=2000&auto=format&fit=crop',
    description: 'Exceptional work-life balance in one of the world\'s most resilient economies.',
    economy: 'Highly developed market economy with strong banking, mining, and healthcare sectors. High GDP per capita.',
    jobMarket: 'High wages and strong demand for medical staff, civil engineers, and trade specialists (plumbers, electricians).',
    education: 'Major global destination for international students, particularly in business, tech, and medicine.',
    prBenefits: 'Access to Medicare (healthcare), world-class infrastructure, and a sunny, outdoor-centric lifestyle.',
    history: 'Initially home to the world\'s oldest living cultures (Indigenous Australians), the nation developed into a modern multicultural federation.',
    geography: 'A continent-country with unique biodiversity, spanning from tropical rainforests to the vast Outback and iconic coastal cities.',
    politics: 'A federal parliamentary constitutional monarchy with a high standard of living and social stability.',
    studentInfo: 'Australia offers "Temporary Graduate" visas that allow students to stay and work for several years after completing their degree.',
    jobInfo: 'The Skilled Independent (189) and Skilled Nominated (190) visas provide direct paths to permanent residency for eligible workers.',
    cities: [
      'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 
      'Gold Coast', 'Hobart', 'Darwin', 'Newcastle', 'Wollongong'
    ],
    visas: [
      {
        id: 'au-189',
        name: 'Skilled Independent (189)',
        purpose: 'Direct Permanent Residency via points.',
        eligibility: ['Invite only', 'Under 45', 'Skill assessment'],
        qualifications: 'Relevant qualification for listed occupation.',
        experience: 'Typically 3+ years required for points.',
        language: 'IELTS 7.0+ (Superior English).',
        finance: '$30,000 AUD+ recommended.',
        processingTime: '12-18 months',
        settlementPotential: true
      },
      {
        id: 'au-482',
        name: 'TSS Worker (482)',
        purpose: 'Temporary employer-sponsored work.',
        eligibility: ['Nomination by employer', 'Relevant skills', 'Health insurance'],
        qualifications: 'Relevant diploma or degree.',
        experience: '2 years relevant work.',
        language: 'IELTS 5.0 overall.',
        finance: 'Self-sufficient.',
        processingTime: '1-3 months',
        settlementPotential: true
      },
      {
        id: 'au-188',
        name: 'Business Innovation (188)',
        purpose: 'For entrepreneurs and investors.',
        eligibility: ['Under 55', 'Nomination by State/Territory', 'Points test'],
        qualifications: 'N/A',
        experience: 'Successful business or investment history.',
        language: 'Vocational English.',
        finance: 'Net assets of $1.25M AUD+.',
        processingTime: '12-24 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'nz',
    name: 'New Zealand',
    flag: '🇳🇿',
    image: 'https://images.unsplash.com/photo-1469521669194-babb45599def?q=80&w=2000&auto=format&fit=crop',
    description: 'Safe, scenic, and supportive environment for families and professionals.',
    economy: 'Stable and open economy, heavily reliant on international trade, agriculture, and a growing tech sector.',
    jobMarket: 'The "Green List" identifies high-priority roles like doctors, engineers, and ICT managers with fast-tracked residency paths.',
    education: 'Known for high-quality, student-centered education with a strong emphasis on practical learning and research.',
    prBenefits: 'Universal healthcare, safe communities, stunning natural beauty, and a very straightforward path to citizenship.',
    history: 'A nation defined by the Treaty of Waitangi between the Māori and the British Crown, fostering a unique bicultural identity.',
    geography: 'An archipelago in the South Pacific known for its dramatic volcanic peaks, lush green valleys, and pristine coastlines.',
    politics: 'A unitary parliamentary representative democracy under a constitutional monarchy, often ranked among the least corrupt in the world.',
    studentInfo: 'Students can benefit from post-study work rights of up to 3 years depending on the level of qualification earned.',
    jobInfo: 'New Zealand is actively seeking skilled workers to fill gaps in construction, healthcare, and software development.',
    cities: [
      'Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 
      'Dunedin', 'Palmerston North', 'Nelson'
    ],
    visas: [
      {
        id: 'nz-sm',
        name: 'Skilled Migrant Category',
        purpose: 'Points-based resident visa.',
        eligibility: ['6 points from job/study/exp', 'Job offer in NZ', 'Age under 55'],
        qualifications: 'Degree level 7+ or relevant vocation.',
        experience: 'Skill-dependent.',
        language: 'IELTS 6.5+.',
        finance: 'Settlement funds required.',
        processingTime: '6-9 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'jp',
    name: 'Japan',
    flag: '🇯🇵',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2000&auto=format&fit=crop',
    description: 'A blend of deep tradition and cutting-edge future tech with new talent visas.',
    economy: 'Third-largest economy in the world, a leader in robotics, automotive engineering, and electronics.',
    jobMarket: 'Rapidly opening up to international talent through the "J-Find" and specialized professional visas to combat labor shortages.',
    education: 'Highly respected engineering, design, and language programs at institutions like University of Tokyo.',
    prBenefits: 'High levels of safety, incredible public transport, world-class healthcare, and a fascinating culture.',
    history: 'A civilization with thousands of years of imperial history that modernized rapidly to become an industrial superpower.',
    geography: 'A volcanic archipelago with four main islands, featuring mountainous terrain and a wide range of climates from snowy Hokkaido to subtropical Okinawa.',
    politics: 'A constitutional monarchy where the Emperor is the symbol of the State and the Prime Minister leads the government.',
    studentInfo: 'The MEXT scholarship and various university programs make Japan an affordable and prestigious destination for research.',
    jobInfo: 'Tech talent is in high demand in Tokyo and Osaka. Proficiency in Japanese is often required but many global tech firms now use English.',
    cities: [
      'Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo'
    ],
    visas: [
      {
        id: 'jp-hsfp',
        name: 'Highly Skilled Professional',
        purpose: 'Points-based fast track to PR.',
        eligibility: ['Academic/Research/Management', '70+ points in system'],
        qualifications: 'Masters or PhD preferred.',
        experience: '3-10 years dependent on role.',
        language: 'JLPT N1/N2 gives extra points.',
        finance: 'Minimum 3M JPY salary.',
        processingTime: '1 month',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'nl',
    name: 'Netherlands',
    flag: '🇳🇱',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?q=80&w=2000&auto=format&fit=crop',
    description: 'Highly liberal, tech-forward, and English-friendly European hub.',
    economy: 'Top-tier logistics and financial hub with a strong focus on sustainability, water management, and high-tech manufacturing.',
    jobMarket: 'Excellent for English speakers. Amsterdam and Eindhoven are major European tech hubs for startups and multinational HQs.',
    education: 'Offers more English-taught programs than any other non-English speaking country in Europe.',
    prBenefits: '30% tax ruling for high-skilled migrants, excellent cycling infrastructure, and the highest English proficiency in the world.',
    history: 'A maritime empire that led the world in trade during the 17th century and evolved into a beacon of social tolerance.',
    geography: 'A low-lying coastal country, famous for its reclaimed land, intricate canal systems, and innovative coastal defenses.',
    politics: 'A constitutional monarchy and a decentralized unitary parliamentary representative democracy.',
    studentInfo: 'The "Orientation Year" visa allows graduates from the top 200 world universities to live and work in the Netherlands for a year.',
    jobInfo: 'Highly Skilled Migrant visas are processed very quickly by the IND, making it one of the easiest EU countries for relocation.',
    cities: [
      'Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'
    ],
    visas: [
      {
        id: 'nl-hsm',
        name: 'Highly Skilled Migrant',
        purpose: 'Work residency for recognized sponsors.',
        eligibility: ['Job offer from sponsor', 'Salary threshold (€5,331 for 30+)', 'Valid passport'],
        qualifications: 'Professional standing.',
        experience: 'Relevant to role.',
        language: 'N/A (English common in work).',
        finance: 'Employment contract salary.',
        processingTime: '2-4 weeks',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'ae',
    name: 'UAE',
    flag: '🇦🇪',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=2000&auto=format&fit=crop',
    description: 'Tax-free salaries and ultra-modern lifestyle in a global trade nexus.',
    economy: 'Wealthy and diversifying rapidly away from oil into tourism, aviation, finance, and green technologies.',
    jobMarket: 'Huge demand for construction, digital marketing, finance professionals, and specialized medical staff in Dubai and Abu Dhabi.',
    education: 'Becoming a regional education hub with satellite campuses from top universities like NYU and Sorbonne.',
    prBenefits: 'Zero personal income tax, 10-year Golden Visas for investors and high-achievers, and ultra-safe luxury lifestyle.',
    history: 'A federation of seven emirates that united in 1971 and transformed from desert tribal lands to global cosmopolitan cities.',
    geography: 'Located on the Arabian Peninsula, featuring dramatic desert dunes and a long coastline on the Persian Gulf.',
    politics: 'A federal absolute monarchy where each emirate maintains significant autonomy under the Supreme Council.',
    studentInfo: 'The UAE is a popular choice for students seeking international business and hospitality degrees in a truly global environment.',
    jobInfo: 'Employment visas are typically tied to sponsorship, but the new Green Visa offers more flexibility for residents and freelancers.',
    cities: [
      'Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman'
    ],
    visas: [
      {
        id: 'ae-gv',
        name: 'Golden Visa',
        purpose: 'Long-term 10-year residency.',
        eligibility: ['Top graduates (GPA 3.8+)', 'Specialized talents', 'Investors'],
        qualifications: 'High degree or proof of talent.',
        experience: 'Varies.',
        language: 'N/A',
        finance: 'AED 30k+ salary or AED 2M investment.',
        processingTime: '1 month',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'sg',
    name: 'Singapore',
    flag: '🇸🇬',
    image: 'https://images.unsplash.com/photo-1565967511849-76a60a516170?q=80&w=2000&auto=format&fit=crop',
    description: 'The gateway to Asia with unparalleled efficiency and financial status.',
    economy: 'A global financial services, port logistics, and technology hub with one of the highest GDPs per capita in the world.',
    jobMarket: 'Intense competition for roles in fintech, AI, biotechnology, and wealth management.',
    education: 'Consistently ranked at the very top of global education metrics (PISA scores) and home to NUS and NTU.',
    prBenefits: 'Low personal taxes, clean and safe environment, world-class airport, and central travel location for Asia.',
    history: 'A former British trading post that gained independence in 1965 and achieved a "miracle" development under Lee Kuan Yew.',
    geography: 'A small city-state island located at the southern tip of the Malay Peninsula, known as the "Garden City" for its green urbanism.',
    politics: 'A unitary parliamentary republic with a high level of government efficiency and social order.',
    studentInfo: 'Singapore is a major research hub, offering numerous scholarships for international graduate students in STEM fields.',
    jobInfo: 'The "ONE Pass" is designed for top-tier global talent, while the Employment Pass (EP) remains the primary route for professionals.',
    cities: ['Singapore City'],
    visas: [
      {
        id: 'sg-ep',
        name: 'Employment Pass',
        purpose: 'For high-earning foreign professionals.',
        eligibility: ['Fixed monthly salary $5k+', 'Degree from good institution', 'COMPASS points'],
        qualifications: 'University degree (verification required).',
        experience: 'Relevant years increase required salary.',
        language: 'English proficient.',
        finance: 'Self-sufficient salary.',
        processingTime: '3-8 weeks',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'ie',
    name: 'Ireland',
    flag: '🇮🇪',
    image: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?q=80&w=2000&auto=format&fit=crop',
    description: 'The "Silicon Valley of Europe" with a rich cultural heritage and welcoming atmosphere.',
    economy: 'One of the fastest-growing economies in the Eurozone, driven by the technology, pharmaceutical, and financial services sectors.',
    jobMarket: 'Home to the European headquarters of many tech giants (Google, Meta, Apple), creating a high demand for IT and software talent.',
    education: 'Prestigious universities like Trinity College Dublin and University College Dublin offer world-class education and research opportunities.',
    prBenefits: 'Path to permanent residency and citizenship, access to the EU market, and a high quality of life with beautiful landscapes.',
    history: 'A nation with a complex history of struggle and resilience, evolving from a rural society to a modern, tech-driven global hub.',
    geography: 'Known as the "Emerald Isle" for its lush green landscapes, rugged coastlines, and vibrant cities.',
    politics: 'A parliamentary republic and a member of the European Union, known for its neutral stance and strong social values.',
    studentInfo: 'The Third Level Graduate Scheme allows international students to stay and work in Ireland for up to 2 years after graduation.',
    jobInfo: 'The Critical Skills Employment Permit is designed to attract highly skilled workers in sectors with identified labor shortages.',
    cities: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford'],
    visas: [
      {
        id: 'ie-csp',
        name: 'Critical Skills Employment Permit',
        purpose: 'For highly skilled professionals in demand.',
        eligibility: ['Job offer in eligible occupation', 'Minimum salary €38,000', 'Relevant degree'],
        qualifications: 'Relevant degree or higher.',
        experience: 'Relevant to the job offer.',
        language: 'English proficiency.',
        finance: 'N/A (Salary based).',
        processingTime: '8-12 weeks',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'fr',
    name: 'France',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=2000&auto=format&fit=crop',
    description: 'A global center for art, science, and industry with a high quality of life.',
    economy: 'One of the world\'s largest economies, with strong sectors in aerospace, luxury goods, energy, and agriculture.',
    jobMarket: 'Growing tech scene (Station F) and demand for engineers, researchers, and healthcare professionals.',
    education: 'Home to prestigious "Grandes Écoles" and world-class universities like Sorbonne and PSL.',
    prBenefits: 'Excellent social security, healthcare, and a 5-year path to permanent residency and citizenship.',
    history: 'A nation that has shaped global history through its revolutions, philosophy, and contributions to art and science.',
    geography: 'The largest country in the EU, featuring diverse landscapes from the Alps to the Mediterranean coast.',
    politics: 'A semi-presidential republic and a key member of the EU and UN Security Council.',
    studentInfo: 'The "Passeport Talent" visa offers a simplified route for researchers, artists, and highly skilled graduates.',
    jobInfo: 'France is actively promoting its "French Tech" ecosystem, offering various incentives for international tech talent.',
    cities: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Bordeaux', 'Lille'],
    visas: [
      {
        id: 'fr-pt',
        name: 'Passeport Talent',
        purpose: 'For highly skilled workers, researchers, and creators.',
        eligibility: ['Master\'s degree or higher', 'Job offer with salary threshold', 'Innovative project'],
        qualifications: 'Higher education degree.',
        experience: 'Relevant to the talent category.',
        language: 'French not always required for tech/research.',
        finance: 'Salary based.',
        processingTime: '2-4 months',
        settlementPotential: true
      }
    ]
  },
  {
    id: 'se',
    name: 'Sweden',
    flag: '🇸🇪',
    image: 'https://images.unsplash.com/photo-1509339022327-1e1e25360a41?q=80&w=2000&auto=format&fit=crop',
    description: 'A pioneer in sustainability, innovation, and social welfare.',
    economy: 'A highly developed, export-oriented economy with strong sectors in telecommunications, automotive, and green tech.',
    jobMarket: 'High demand for software engineers, clean energy specialists, and healthcare workers in a flat-hierarchy work culture.',
    education: 'Renowned for its innovative and student-centered approach, with top universities like Karolinska Institute and Lund University.',
    prBenefits: 'World-leading social welfare, generous parental leave, and a high standard of living in a safe environment.',
    history: 'From its Viking roots to its modern status as a neutral, prosperous social democracy and a leader in global innovation.',
    geography: 'A Nordic country with vast forests, thousands of islands, and dramatic arctic landscapes in the north.',
    politics: 'A constitutional monarchy and parliamentary democracy with a strong emphasis on equality and human rights.',
    studentInfo: 'International students can stay for up to 12 months after graduation to look for work or start a business.',
    jobInfo: 'Sweden offers a straightforward work permit system for those with a job offer from a Swedish employer.',
    cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
    visas: [
      {
        id: 'se-wp',
        name: 'Work Permit',
        purpose: 'For those with a job offer in Sweden.',
        eligibility: ['Job offer with salary min 27,360 SEK', 'Insurance coverage', 'Advertised in EU/EEA'],
        qualifications: 'Relevant to the role.',
        experience: 'Relevant to the role.',
        language: 'English often sufficient in tech.',
        finance: 'Salary based.',
        processingTime: '2-4 months',
        settlementPotential: true
      }
    ]
  }
];

export const COUNTRY_CODES = [
  { code: '+93', country: 'Afghanistan' },
  { code: '+355', country: 'Albania' },
  { code: '+213', country: 'Algeria' },
  { code: '+376', country: 'Andorra' },
  { code: '+244', country: 'Angola' },
  { code: '+1-264', country: 'Anguilla' },
  { code: '+1-268', country: 'Antigua and Barbuda' },
  { code: '+54', country: 'Argentina' },
  { code: '+374', country: 'Armenia' },
  { code: '+297', country: 'Aruba' },
  { code: '+61', country: 'Australia' },
  { code: '+43', country: 'Austria' },
  { code: '+994', country: 'Azerbaijan' },
  { code: '+1-242', country: 'Bahamas' },
  { code: '+973', country: 'Bahrain' },
  { code: '+880', country: 'Bangladesh' },
  { code: '+1-246', country: 'Barbados' },
  { code: '+375', country: 'Belarus' },
  { code: '+32', country: 'Belgium' },
  { code: '+501', country: 'Belize' },
  { code: '+229', country: 'Benin' },
  { code: '+1-441', country: 'Bermuda' },
  { code: '+975', country: 'Bhutan' },
  { code: '+591', country: 'Bolivia' },
  { code: '+387', country: 'Bosnia and Herzegovina' },
  { code: '+267', country: 'Botswana' },
  { code: '+55', country: 'Brazil' },
  { code: '+1-284', country: 'British Virgin Islands' },
  { code: '+673', country: 'Brunei' },
  { code: '+359', country: 'Bulgaria' },
  { code: '+226', country: 'Burkina Faso' },
  { code: '+257', country: 'Burundi' },
  { code: '+855', country: 'Cambodia' },
  { code: '+237', country: 'Cameroon' },
  { code: '+1', country: 'Canada' },
  { code: '+238', country: 'Cape Verde' },
  { code: '+1-345', country: 'Cayman Islands' },
  { code: '+236', country: 'Central African Republic' },
  { code: '+235', country: 'Chad' },
  { code: '+56', country: 'Chile' },
  { code: '+86', country: 'China' },
  { code: '+57', country: 'Colombia' },
  { code: '+269', country: 'Comoros' },
  { code: '+682', country: 'Cook Islands' },
  { code: '+506', country: 'Costa Rica' },
  { code: '+385', country: 'Croatia' },
  { code: '+53', country: 'Cuba' },
  { code: '+357', country: 'Cyprus' },
  { code: '+420', country: 'Czech Republic' },
  { code: '+243', country: 'Democratic Republic of the Congo' },
  { code: '+45', country: 'Denmark' },
  { code: '+253', country: 'Djibouti' },
  { code: '+1-767', country: 'Dominica' },
  { code: '+1-809', country: 'Dominican Republic' },
  { code: '+593', country: 'Ecuador' },
  { code: '+20', country: 'Egypt' },
  { code: '+503', country: 'El Salvador' },
  { code: '+240', country: 'Equatorial Guinea' },
  { code: '+291', country: 'Eritrea' },
  { code: '+372', country: 'Estonia' },
  { code: '+251', country: 'Ethiopia' },
  { code: '+679', country: 'Fiji' },
  { code: '+358', country: 'Finland' },
  { code: '+33', country: 'France' },
  { code: '+241', country: 'Gabon' },
  { code: '+220', country: 'Gambia' },
  { code: '+995', country: 'Georgia' },
  { code: '+49', country: 'Germany' },
  { code: '+233', country: 'Ghana' },
  { code: '+350', country: 'Gibraltar' },
  { code: '+30', country: 'Greece' },
  { code: '+299', country: 'Greenland' },
  { code: '+1-473', country: 'Grenada' },
  { code: '+502', country: 'Guatemala' },
  { code: '+224', country: 'Guinea' },
  { code: '+245', country: 'Guinea-Bissau' },
  { code: '+592', country: 'Guyana' },
  { code: '+509', country: 'Haiti' },
  { code: '+504', country: 'Honduras' },
  { code: '+852', country: 'Hong Kong' },
  { code: '+36', country: 'Hungary' },
  { code: '+354', country: 'Iceland' },
  { code: '+91', country: 'India' },
  { code: '+62', country: 'Indonesia' },
  { code: '+98', country: 'Iran' },
  { code: '+964', country: 'Iraq' },
  { code: '+353', country: 'Ireland' },
  { code: '+972', country: 'Israel' },
  { code: '+39', country: 'Italy' },
  { code: '+225', country: 'Ivory Coast' },
  { code: '+1-876', country: 'Jamaica' },
  { code: '+81', country: 'Japan' },
  { code: '+962', country: 'Jordan' },
  { code: '+7', country: 'Kazakhstan' },
  { code: '+254', country: 'Kenya' },
  { code: '+686', country: 'Kiribati' },
  { code: '+965', country: 'Kuwait' },
  { code: '+996', country: 'Kyrgyzstan' },
  { code: '+856', country: 'Laos' },
  { code: '+371', country: 'Latvia' },
  { code: '+961', country: 'Lebanon' },
  { code: '+266', country: 'Lesotho' },
  { code: '+231', country: 'Liberia' },
  { code: '+218', country: 'Libya' },
  { code: '+423', country: 'Liechtenstein' },
  { code: '+370', country: 'Lithuania' },
  { code: '+352', country: 'Luxembourg' },
  { code: '+853', country: 'Macau' },
  { code: '+389', country: 'Macedonia' },
  { code: '+261', country: 'Madagascar' },
  { code: '+265', country: 'Malawi' },
  { code: '+60', country: 'Malaysia' },
  { code: '+960', country: 'Maldives' },
  { code: '+223', country: 'Mali' },
  { code: '+356', country: 'Malta' },
  { code: '+692', country: 'Marshall Islands' },
  { code: '+222', country: 'Mauritania' },
  { code: '+230', country: 'Mauritius' },
  { code: '+52', country: 'Mexico' },
  { code: '+691', country: 'Micronesia' },
  { code: '+373', country: 'Moldova' },
  { code: '+377', country: 'Monaco' },
  { code: '+976', country: 'Mongolia' },
  { code: '+382', country: 'Montenegro' },
  { code: '+1-664', country: 'Montserrat' },
  { code: '+212', country: 'Morocco' },
  { code: '+258', country: 'Mozambique' },
  { code: '+95', country: 'Myanmar' },
  { code: '+264', country: 'Namibia' },
  { code: '+674', country: 'Nauru' },
  { code: '+977', country: 'Nepal' },
  { code: '+31', country: 'Netherlands' },
  { code: '+687', country: 'New Caledonia' },
  { code: '+64', country: 'New Zealand' },
  { code: '+505', country: 'Nicaragua' },
  { code: '+227', country: 'Niger' },
  { code: '+234', country: 'Nigeria' },
  { code: '+683', country: 'Niue' },
  { code: '+850', country: 'North Korea' },
  { code: '+47', country: 'Norway' },
  { code: '+968', country: 'Oman' },
  { code: '+92', country: 'Pakistan' },
  { code: '+680', country: 'Palau' },
  { code: '+970', country: 'Palestine' },
  { code: '+507', country: 'Panama' },
  { code: '+675', country: 'Papua New Guinea' },
  { code: '+595', country: 'Paraguay' },
  { code: '+51', country: 'Peru' },
  { code: '+63', country: 'Philippines' },
  { code: '+48', country: 'Poland' },
  { code: '+351', country: 'Portugal' },
  { code: '+1-787', country: 'Puerto Rico' },
  { code: '+974', country: 'Qatar' },
  { code: '+242', country: 'Republic of the Congo' },
  { code: '+262', country: 'Reunion' },
  { code: '+40', country: 'Romania' },
  { code: '+7', country: 'Russia' },
  { code: '+250', country: 'Rwanda' },
  { code: '+1-869', country: 'Saint Kitts and Nevis' },
  { code: '+1-758', country: 'Saint Lucia' },
  { code: '+1-784', country: 'Saint Vincent and the Grenadines' },
  { code: '+685', country: 'Samoa' },
  { code: '+378', country: 'San Marino' },
  { code: '+239', country: 'Sao Tome and Principe' },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+221', country: 'Senegal' },
  { code: '+381', country: 'Serbia' },
  { code: '+248', country: 'Seychelles' },
  { code: '+232', country: 'Sierra Leone' },
  { code: '+65', country: 'Singapore' },
  { code: '+421', country: 'Slovakia' },
  { code: '+386', country: 'Slovenia' },
  { code: '+677', country: 'Solomon Islands' },
  { code: '+252', country: 'Somalia' },
  { code: '+27', country: 'South Africa' },
  { code: '+82', country: 'South Korea' },
  { code: '+211', country: 'South Sudan' },
  { code: '+34', country: 'Spain' },
  { code: '+94', country: 'Sri Lanka' },
  { code: '+249', country: 'Sudan' },
  { code: '+597', country: 'Suriname' },
  { code: '+268', country: 'Swaziland' },
  { code: '+46', country: 'Sweden' },
  { code: '+41', country: 'Switzerland' },
  { code: '+963', country: 'Syria' },
  { code: '+886', country: 'Taiwan' },
  { code: '+992', country: 'Tajikistan' },
  { code: '+255', country: 'Tanzania' },
  { code: '+66', country: 'Thailand' },
  { code: '+228', country: 'Togo' },
  { code: '+676', country: 'Tonga' },
  { code: '+1-868', country: 'Trinidad and Tobago' },
  { code: '+216', country: 'Tunisia' },
  { code: '+90', country: 'Turkey' },
  { code: '+993', country: 'Turkmenistan' },
  { code: '+1-649', country: 'Turks and Caicos Islands' },
  { code: '+688', country: 'Tuvalu' },
  { code: '+256', country: 'Uganda' },
  { code: '+380', country: 'Ukraine' },
  { code: '+971', country: 'United Arab Emirates' },
  { code: '+44', country: 'United Kingdom' },
  { code: '+1', country: 'United States' },
  { code: '+598', country: 'Uruguay' },
  { code: '+998', country: 'Uzbekistan' },
  { code: '+678', country: 'Vanuatu' },
  { code: '+379', country: 'Vatican City' },
  { code: '+58', country: 'Venezuela' },
  { code: '+84', country: 'Vietnam' },
  { code: '+967', country: 'Yemen' },
  { code: '+260', country: 'Zambia' },
  { code: '+263', country: 'Zimbabwe' },
].sort((a, b) => a.country.localeCompare(b.country));

export const FIELDS_OF_STUDY = [
  'Computer Science',
  'Data Science',
  'Artificial Intelligence',
  'Business Administration',
  'Finance',
  'Marketing',
  'Mechanical Engineering',
  'Civil Engineering',
  'Electrical Engineering',
  'Medicine',
  'Nursing',
  'Psychology',
  'Law',
  'Education',
  'Architecture',
  'Environmental Science',
  'Biotechnology',
  'Social Work',
  'International Relations',
  'Economics',
  'Other'
];

export const CONSULTANCIES: Consultancy[] = [
  {
    id: '1',
    name: 'Global Pathways Inc.',
    location: 'London / Toronto',
    countries: ['UK', 'Canada'],
    specialties: ['Express Entry', 'Skilled Worker'],
    rating: 4.8,
    contact: '+44 20 1234 5678',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    name: 'EuroLink Immigration',
    location: 'Berlin / Dubai',
    countries: ['Germany', 'UAE'],
    specialties: ['Job Seeker', 'Blue Card'],
    rating: 4.6,
    contact: '+49 30 9876 5432',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800'
  }
];
