import React, { useState, useEffect } from 'react';
import { api } from '../../services/api';
import CloudflareAnalytics from './CloudflareAnalytics';

interface Analytics {
  totalUsers: number;
  totalAssessments: number;
  recentUsers: number;
  popularDestinations: { country: string; count: number }[];
  averageScore: number;
  activeUsers: number;
}

interface Props {
  onNavigate: (page: string) => void;
}

const AdminDashboard: React.FC<Props> = ({ onNavigate }) => {
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAnalytics = async () => {
      try {
        const data = await api.admin.getAnalytics();
        setAnalytics(data);
      } catch (err) {
        console.error('Failed to fetch analytics:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchAnalytics();
  }, []);

  const StatCard = ({ title, value, subtitle, icon }: { title: string; value: string | number; subtitle?: string; icon: string }) => (
    <div className="bg-white p-6 rounded-2xl shadow-lg border border-slate-100 hover:shadow-xl transition-shadow">
      <div className="flex items-start justify-between mb-4">
        <div>
          <p className="text-xs font-black uppercase tracking-widest text-slate-500">{title}</p>
          <h3 className="text-3xl font-black text-slate-900 mt-2">{value}</h3>
          {subtitle && <p className="text-xs text-slate-500 mt-1">{subtitle}</p>}
        </div>
        <div className="text-4xl">{icon}</div>
      </div>
    </div>
  );

  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      <div className="flex justify-between items-center mb-10">
        <div>
          <h1 className="text-4xl font-black text-slate-900 uppercase tracking-tighter">Admin Dashboard</h1>
          <p className="text-slate-500 mt-2">Monitor and manage your GlobalVisa AI platform</p>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-20">
          <div className="w-16 h-16 border-4 border-[#FF8B60] border-t-transparent rounded-full animate-spin mx-auto"></div>
          <p className="mt-4 text-slate-500 font-bold">Loading analytics...</p>
        </div>
      ) : analytics ? (
        <div className="space-y-8">
          {/* Statistics Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <StatCard 
              title="Total Users" 
              value={analytics.totalUsers} 
              subtitle={`${analytics.activeUsers} with assessments`}
              icon="👥" 
            />
            <StatCard 
              title="Total Assessments" 
              value={analytics.totalAssessments} 
              subtitle="Generated by all users"
              icon="📊" 
            />
            <StatCard 
              title="New Users (7 days)" 
              value={analytics.recentUsers} 
              subtitle="Recent signups"
              icon="✨" 
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <StatCard 
              title="Average Eligibility" 
              value={`${analytics.averageScore}%`} 
              subtitle="Across all assessments"
              icon="📈" 
            />
            <StatCard 
              title="Active Users" 
              value={analytics.activeUsers} 
              subtitle="Users with completed assessments"
              icon="⚡" 
            />
          </div>

          {/* Popular Destinations */}
          <div className="bg-white p-8 rounded-2xl shadow-lg border border-slate-100">
            <h2 className="text-xl font-black text-slate-900 uppercase tracking-tighter mb-6">Popular Destinations</h2>
            {analytics.popularDestinations.length > 0 ? (
              <div className="space-y-4">
                {analytics.popularDestinations.map((dest, index) => (
                  <div key={index} className="flex items-center justify-between py-3 border-b border-slate-100 last:border-0">
                    <div className="flex items-center space-x-4">
                      <div className="w-8 h-8 rounded-full bg-[#FF8B60] text-white flex items-center justify-center font-black text-sm">
                        {index + 1}
                      </div>
                      <span className="font-bold text-slate-900">{dest.country}</span>
                    </div>
                    <div className="text-right">
                      <span className="text-2xl font-black text-slate-900">{dest.count}</span>
                      <p className="text-xs text-slate-500">assessments</p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-500 italic text-center py-8">No assessment data yet</p>
            )}
          </div>

          {/* Quick Actions */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <button
              onClick={() => onNavigate('admin-users')}
              className="bg-gradient-to-r from-[#FF8B60] to-orange-500 text-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all group"
            >
              <div className="flex items-center justify-between">
                <div className="text-left">
                  <h3 className="text-2xl font-black uppercase">User Management</h3>
                  <p className="text-white/80 mt-2">View and manage all users</p>
                </div>
                <span className="text-5xl group-hover:scale-110 transition-transform">👤</span>
              </div>
            </button>

            <button
              onClick={() => onNavigate('admin-countries')}
              className="bg-gradient-to-r from-blue-600 to-blue-700 text-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all group"
            >
              <div className="flex items-center justify-between">
                <div className="text-left">
                  <h3 className="text-2xl font-black uppercase">Country Management</h3>
                  <p className="text-white/80 mt-2">Add and manage countries</p>
                </div>
                <span className="text-5xl group-hover:scale-110 transition-transform">🌍</span>
              </div>
            </button>

            <button
              onClick={() => onNavigate('admin-settings')}
              className="bg-gradient-to-r from-slate-800 to-slate-900 text-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all group"
            >
              <div className="flex items-center justify-between">
                <div className="text-left">
                  <h3 className="text-2xl font-black uppercase">Settings</h3>
                  <p className="text-white/80 mt-2">Configure platform settings</p>
                </div>
                <span className="text-5xl group-hover:scale-110 transition-transform">⚙️</span>
              </div>
            </button>
          </div>

          {/* Cloudflare Analytics Section */}
          <div className="mt-8">
            <CloudflareAnalytics />
          </div>
        </div>
      ) : (
        <div className="text-center text-red-500 py-20">
          <p className="text-xl font-bold">Failed to load analytics</p>
          <button 
            onClick={() => window.location.reload()} 
            className="mt-4 px-6 py-3 bg-[#FF8B60] text-white rounded-xl font-bold hover:bg-orange-500"
          >
            Retry
          </button>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;
