
import React from 'react';
import { motion } from 'motion/react';
import ITNextLogo from './Logo';

const TermsOfService: React.FC = () => {
  const sections = [
    {
      title: "Acceptance of Terms",
      icon: "fa-handshake-simple",
      content: [
        "By accessing or using ITNEXT GlobalVisa AI (\"the Service\"), you agree to be bound by these Terms of Service.",
        "If you do not agree to these terms, you must not access or use the Service.",
        "We reserve the right to modify these terms at any time. Continued use of the Service after modifications constitutes acceptance of the updated terms.",
        "You must be at least 16 years old to use the Service."
      ]
    },
    {
      title: "Account Registration",
      icon: "fa-user-plus",
      content: [
        "You may be required to create an account to access certain features of the Service.",
        "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
        "You agree to provide accurate, current, and complete information during the registration process.",
        "We reserve the right to suspend or terminate accounts that violate these terms or engage in fraudulent activity."
      ]
    },
    {
      title: "Use of the Service",
      icon: "fa-laptop-code",
      content: [
        "The Service provides AI-powered visa eligibility assessments, university search, job search, and related immigration guidance tools.",
        "All assessments and recommendations are generated by AI and are for informational purposes only. They do not constitute legal, immigration, or professional advice.",
        "You should always consult with qualified immigration lawyers or licensed consultants before making any visa or relocation decisions.",
        "You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, or impair the Service.",
        "You must not attempt to gain unauthorized access to any part of the Service, other users' accounts, or any systems or networks connected to the Service."
      ]
    },
    {
      title: "AI-Generated Content Disclaimer",
      icon: "fa-robot",
      content: [
        "Our platform uses Google Gemini AI to generate eligibility assessments and recommendations.",
        "AI-generated results are based on the information you provide and publicly available data. They may not reflect the most current immigration policies or regulations.",
        "ITNEXT does not guarantee the accuracy, completeness, or reliability of any AI-generated content.",
        "Eligibility scores and recommendations should be treated as preliminary guidance, not definitive outcomes.",
        "Immigration policies change frequently; always verify results with official government sources or qualified professionals."
      ]
    },
    {
      title: "Intellectual Property",
      icon: "fa-copyright",
      content: [
        "All content, features, and functionality of the Service — including but not limited to text, graphics, logos, icons, software, and design — are the exclusive property of ITNEXT and are protected by copyright, trademark, and other intellectual property laws.",
        "You may not reproduce, distribute, modify, create derivative works from, or commercially exploit any part of the Service without our express written permission.",
        "User-generated content (such as profile data and feedback) remains the property of the user, but you grant ITNEXT a non-exclusive, worldwide license to use this data to provide and improve the Service."
      ]
    },
    {
      title: "Limitation of Liability",
      icon: "fa-scale-balanced",
      content: [
        "The Service is provided on an \"AS IS\" and \"AS AVAILABLE\" basis without warranties of any kind, either express or implied.",
        "ITNEXT shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.",
        "We do not warrant that the Service will be uninterrupted, timely, secure, or error-free.",
        "In no event shall ITNEXT's total liability exceed the amount you have paid to ITNEXT in the twelve (12) months preceding the claim.",
        "Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you."
      ]
    },
    {
      title: "Privacy & Data Usage",
      icon: "fa-lock",
      content: [
        "Your use of the Service is also governed by our Privacy Policy, which describes how we collect, use, and protect your personal information.",
        "By using the Service, you consent to the collection and use of your data as described in our Privacy Policy.",
        "We take reasonable measures to protect your data, but we cannot guarantee absolute security of information transmitted over the internet."
      ]
    },
    {
      title: "Termination",
      icon: "fa-ban",
      content: [
        "We may terminate or suspend your access to the Service immediately, without prior notice, for any reason including breach of these Terms.",
        "Upon termination, your right to use the Service will cease immediately.",
        "You may terminate your account at any time by contacting us and requesting account deletion.",
        "All provisions of these Terms that should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnity, and limitations of liability."
      ]
    },
    {
      title: "Governing Law",
      icon: "fa-gavel",
      content: [
        "These Terms shall be governed by and construed in accordance with the laws of Sri Lanka, without regard to its conflict of law provisions.",
        "Any disputes arising from or related to these Terms or the Service shall be resolved through good-faith negotiation first, and if necessary, through the courts of Sri Lanka.",
        "If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white py-20">
      <div className="max-w-5xl mx-auto px-4 space-y-16">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6"
        >
          <div className="flex items-center space-x-3">
            <ITNextLogo hideText className="h-8" />
            <span className="text-[#FF8B60] font-black text-xs uppercase tracking-[0.3em]">Legal</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black text-slate-900 leading-[0.9] tracking-tighter">
            Terms of <span className="text-[#FF8B60]">Service.</span>
          </h1>
          <p className="text-lg text-slate-500 font-medium max-w-2xl">
            Please read these terms carefully before using the ITNEXT GlobalVisa AI platform. By using our services, you agree to be bound by the following terms and conditions.
          </p>
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-slate-100 rounded-full text-xs font-black text-slate-500 uppercase tracking-widest">
            <i className="fas fa-calendar-alt text-[#FF8B60]"></i>
            Last Updated: March 28, 2026
          </div>
        </motion.div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.05 }}
              className="p-8 md:p-10 rounded-[2rem] bg-slate-50 border border-slate-100 space-y-6"
            >
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-white rounded-xl shadow-lg flex items-center justify-center text-[#FF8B60] text-lg">
                  <i className={`fas ${section.icon}`}></i>
                </div>
                <h2 className="text-2xl font-black text-slate-900 tracking-tight">{section.title}</h2>
              </div>
              <ul className="space-y-4">
                {section.content.map((item, j) => (
                  <li key={j} className="flex items-start gap-3 text-slate-600 font-medium leading-relaxed">
                    <div className="w-1.5 h-1.5 rounded-full bg-[#FF8B60] mt-2.5 flex-shrink-0"></div>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

        {/* Contact Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="bg-slate-900 rounded-[3rem] p-10 md:p-16 text-center space-y-6"
        >
          <h2 className="text-3xl md:text-4xl font-black text-white tracking-tighter">Need Clarification?</h2>
          <p className="text-slate-400 font-medium max-w-xl mx-auto">
            If you have questions about these Terms of Service, please don't hesitate to contact our team.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <a href="mailto:legal@itnext-globalvisa.org" className="px-8 py-4 bg-[#FF8B60] text-white rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-[#ff7a4a] transition-all">
              <i className="fas fa-envelope mr-2"></i> Contact Legal Team
            </a>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfService;
